# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’
inhibit_all_warnings!
target ‘Example’ do
pod 'AFNetworking’,’~>3.1.0’
pod 'BaiduMapKit’,’~>3.0.0’
pod 'UMengSocialCOM', '~> 5.2.1'
pod ‘BPushSDK’, '~> 1.4.5’
pod ‘SDWebImage’, '~> 3.8.1’
pod ‘Masonry’, '~> 1.0.1’
pod ‘MJExtension’, '~> 3.0.10’
pod ‘MJRefresh’, '~> 3.1.5’
pod ‘UITableView+FDTemplateLayoutCell’
pod ‘MBProgressHUD’
pod ‘YYText’, '~> 1.0.5’
pod ‘YYImage’, '~> 1.0.2’
pod ‘IQKeyboardManager’
end